---
  - name: 'Instala pacotes do nodejs latest'
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: nodejs
      state: latest
    become: yes
  - name: "baixa chave o yarn"
    shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"      
    become: yes     
  - name: "adiciona a chave do yarn no repositorio"
    shell: 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'      
    become: yes     
  - name: 'Instala o yarn latest'
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: yarn
    become: yes     
  - name: "instala o git..."
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: git
      state: latest
    become: yes
  - name: 'Instala pacotes do docker'
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: docker
      state: latest
    become: yes
  - name: 'Instala pacotes do docker-compose'
    shell: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  - name: 'Inserir permissoes do docker-compose'
    shell: 'sudo chmod +x /usr/local/bin/docker-compose'
    become: yes
  - name: 'Criar atalhos para docker-compose'
    shell: 'sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose'
    become: yes

    
  
    