version: "3"
services:
    node-api:
        image: node:latest
        container_name: node-api
        restart: always
        env_file:
         - .env
        ports:
          - "3000:3000"
        volumes:
          - ./node-api:/var/www
        working_dir: /var/www
        command: yarn install
        command: yarn start
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "5"