version: "3"
services:
    node-api:
        build: ./node-api
        container_name: node-api
        ports:
          - "3000:3000"
        command: yarn install
        command: yarn start
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "5"