version: "3"

services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
        ports:
        - "9090:9090"
        depends_on:
        - exporter

    exporter:
        image: prom/node-exporter:latest
        ports:
        - "9100:9100"

    grafana:
        image: grafana/grafana
        volumes:
            - grafana-storage:/var/lib/grafana
        ports:
        - "4000:3000"
        depends_on:
        - prometheus

volumes:
    grafana-storage: