
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
  end

  config.vm.define "developer" do |v|
	  v.vm.network "private_network", ip: "172.20.1.4"
  end

  config.vm.provider "virtualbox" do |x|
	x.memory = 1024
  end

  config.vm.define "developer" do |x|
	  x.vm.network "private_network", ip: "172.20.1.5"
  end

end